apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: redis-scalable
  namespace: default
spec:
  template:
    # metadata:
    #   annotations:
    #     autoscaling.knative.dev/minScale: "1"
    #     autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: ericarthurblair/redis-benchmark@sha256:9340de6f5e6205703de04fea7236c9922cf02b0f454da5f509245ba6dc6e5c27
          env:
            - name: TASK_SIZE
              value: "100"
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          readinessProbe: null
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
      volumes:
        - name: log-volume
          emptyDir: {}
