apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: alu-bench
  namespace: default
spec:
  template:
    metadata:
      annotations:
        containerConcurrency: "1"  # 指定容器最大并发请求数，默认0表示不限制
        autoscaling.knative.dev/minScale: "128"
        autoscaling.knative.dev/maxScale: "128"
        autoscaling.knative.dev/target: "1"    # 设置每个 Pod 期望的并发数
    spec:
      containers:
        - image: ericarthurblair/alu-bench@sha256:7efabd5847c6fc1327ea11b576d0aa8ec0dd38eb61418e0c26619d04e90f8c1a
          imagePullPolicy: IfNotPresent
          resources:
            limits: # 最大资源
              cpu: "1"
            requests: # 申请资源
              cpu: "1"
          env:
            - name: NODE_OF_ACTIVATOR
              value: "5"
          readinessProbe: null
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
      volumes:
        - name: log-volume
          emptyDir: {}
